global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Add service metrics endpoints here when exposed
  # - job_name: 'api-gateway'
  #   static_configs:
  #     - targets: ['api-gateway:3000']

